### ISSUE TITLE
Annotation: ArrayValue items schema support

### ISSUE THREAD

**Issue by AdamLutka** [ScrumWorks/openapi-schema#4]
```
/**
 * @OA\ArrayValue(itemsSchema=@OA\Integer(mininimum=10, maximum=220))
*/
public array $ints;
```

**Comment by detrandix** [comment]
```
/**
 * @OA\ArrayValue(itemsSchema=@OA\Integer(mininimum=10, maximum=220))
 * @var int[]
*/
public array $ints;
```
provided example var is generic array.

Also is `itemsSchema` good name? Because we provide only annotation, not schema itself...

**Comment by AdamLutka** [comment]
you are right, it's only draft, maybe something like `itemDetails` but I am not good at making identifiers

**Comment by detrandix** [comment]
maybe `itemsAnnotation`?
